/*
 * App URI: AI/test
 * Source Location: AI/test.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.5927), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("AI/test", { 
		onPrepare: function(loader) {
			loader.addScript("tsSupportAI.js");
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/************************************************
			 * test.js
			 * Created at 2025. 12. 4. 오후 4:25:39.
			 *
			 * @author LCM
			 ************************************************/

			/*
			 * "Button" 버튼(btn1)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtn1Click(e){

			    console.log("[테스트] RangeError 발생 시도...");
			    
			    var arr = new Array(-1); // 음수 길이 배열

			};
			// End - User Script
			
			// Header
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023.984px)", "tablet");
			app.supportMedia("all and (max-width: 499.984px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var button_1 = new cpr.controls.Button("btn1");
			button_1.value = "Button";
			if(typeof onBtn1Click == "function") {
				button_1.addEventListener("click", onBtn1Click);
			}
			container.addChild(button_1, {
				"top": "183px",
				"left": "624px",
				"width": "120px",
				"height": "36px"
			});
			
			var comboBox_1 = new cpr.controls.ComboBox("cmb1");
			(function(comboBox_1){
				comboBox_1.addItem(new cpr.controls.Item("label1", "value1"));
			})(comboBox_1);
			container.addChild(comboBox_1, {
				"top": "307px",
				"left": "138px",
				"width": "230px",
				"height": "83px"
			});
			
			var button_2 = new cpr.controls.Button("btn2");
			button_2.value = "Button";
			if(typeof onBtn2Click == "function") {
				button_2.addEventListener("click", onBtn2Click);
			}
			container.addChild(button_2, {
				"top": "329px",
				"left": "513px",
				"width": "169px",
				"height": "69px"
			});
		}
	});
	app.title = "test";
	cpr.core.Platform.INSTANCE.register(app);
})();
