/*
 * App URI: AI/test
 * Source Location: AI/test.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.5927), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("AI/test", { 
		onPrepare: function(loader) {
			loader.addScript("tsSupportAI.js");
			loader.addScript("testExam.js");
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/************************************************
			 * test.js
			 * Created at 2025. 12. 4. 오후 4:25:39.
			 *
			 * @author LCM
			 ************************************************/



			/*
			 * "Button" 버튼(btn2)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtn2Click2(e){
				var btn2 = e.control;
				app.lookup("cmb1").addItem(new cpr.controls.Item("label1","value1"));
			}

			/*
			 * "Button" 버튼(btn1)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtn1Click(e){

			   testRangeError();

			}

			/*
			 * "시나리오 에러" 버튼(btn3)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtn3Click(e){
				var btn3 = e.control;
				runAllScenarioTests();
			};
			// End - User Script
			
			// Header
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023.984px)", "tablet");
			app.supportMedia("all and (max-width: 499.984px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var button_1 = new cpr.controls.Button("btn1");
			button_1.value = "기본 에러";
			if(typeof onBtn1Click == "function") {
				button_1.addEventListener("click", onBtn1Click);
			}
			container.addChild(button_1, {
				"top": "169px",
				"left": "357px",
				"width": "120px",
				"height": "36px"
			});
			
			var comboBox_1 = new cpr.controls.ComboBox("cmb1");
			(function(comboBox_1){
				comboBox_1.addItem(new cpr.controls.Item("label1", "value1"));
			})(comboBox_1);
			container.addChild(comboBox_1, {
				"top": "20px",
				"left": "66px",
				"width": "230px",
				"height": "83px"
			});
			
			var button_2 = new cpr.controls.Button("btn2");
			button_2.value = "Button";
			if(typeof onBtn2Click2 == "function") {
				button_2.addEventListener("click", onBtn2Click2);
			}
			container.addChild(button_2, {
				"top": "20px",
				"left": "349px",
				"width": "169px",
				"height": "69px"
			});
			
			var button_3 = new cpr.controls.Button("btn3");
			button_3.value = "시나리오 에러";
			if(typeof onBtn3Click == "function") {
				button_3.addEventListener("click", onBtn3Click);
			}
			container.addChild(button_3, {
				"top": "251px",
				"left": "357px",
				"width": "120px",
				"height": "36px"
			});
		}
	});
	app.title = "test";
	cpr.core.Platform.INSTANCE.register(app);
})();
